version: "3.7"

services:
  greeting-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: greeting-be-service
    expose:
      - "8080"
    environment:
        - SPRING_PROFILES_ACTIVE=dev