name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
#  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
#  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
#  TASK_DEFINITION: ${{ secrets.TASK_DEFINITION }}
#  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
#  LOG_GROUP_NAME: ${{ secrets.LOG_GROUP_NAME }}
#  LOG_STREAM_PREFIX: ${{ secrets.LOG_STREAM_PREFIX }}


jobs:
  job:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build
        env:
          SPRING_PROFILES_ACTIVE: prod
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: loin-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: docker build
        id: build-docker-image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
          IMAGE_TAG: dev
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_NAME }}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_NAME }}:${IMAGE_TAG}
      

#      - name: Deploy to Amazon ECS
#        id: task-deploy
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#        with:
#          task-definition: ${{ secrets.TASK_DEFINITION }}
#          container-name: ${{ secrets.CONTAINER_NAME }}
#          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest
#          aws-region: ap-northeast-2
#          log-group-name: ${{ secrets.LOG_GROUP_NAME }}
#          log-stream-prefix: ${{ secrets.LOG_STREAM_PREFIX }}
#      - name:
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#        with:
#          task-definition: ${{ secrets.TASK_DEFINITION }}
#          service: ${{ secrets.SERVICE_NAME }}
#          cluster: ${{ secrets.CLUSTER_NAME }}
#          wait-for-service-stability: true
#          aws-region: ap-northeast-2


